[package]
name = "backend-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^4"
actix-cors = "^0.6"
actix-web-lab = "^0.19"
juniper = "0.15"
env_logger = "^0.10"
log = "^0.4"

